import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {randomBytes, pbkdf2Sync} from 'node:crypto';
import {localDB} from './d1-local.mjs';

const module = await import('data:text/javascript;base64,' + (await readFile('dist/server/index.js')).toString('base64'));
const DB = localDB(), env = {DB, BUCKET:{}}, origin = 'https://entity-one.test';
const credentials = {username:'owner-test',password:randomBytes(24).toString('base64url')};
const salt = randomBytes(32).toString('hex'), hash = pbkdf2Sync(credentials.password,salt,600000,32,'sha256').toString('hex');
let assertions = 0;
async function call(route, method='GET', value, auth={}, expected=200) {
  const response = await module.default.fetch(new Request(origin+route,{method,headers:{Origin:origin,'Content-Type':'application/json',...auth},...(value===undefined?{}:{body:JSON.stringify(value)})}),env,{});
  const data = await response.json();
  assert.equal(response.status,expected,route+': '+JSON.stringify(data)); assertions++;
  return {data,response};
}
const authentication = result => ({Cookie:result.response.headers.get('Set-Cookie').split(';')[0],'X-CSRF-Token':result.data.csrfToken});
try {
  await DB.prepare('INSERT INTO administrator(id,username,salt,hash,hash_version) VALUES(1,?,?,?,?)').bind(credentials.username,salt,hash,module.PASSWORD_VERSION).run();
  const owner = authentication(await call('/api/login','POST',credentials));
  const seed = (await call('/api/content')).data;
  const secret = 'PRIVATE-NOTES-MUST-NEVER-ENTER-LOGS';
  const content = structuredClone(seed.content);
  content.listings.push({...content.listings.find(x=>x.type==='inventory'),id:'inventory-draft',status:'draft',internalNotes:secret});
  content.listings.push({...content.listings.find(x=>x.type==='wanted'),id:'wanted-draft',status:'draft',internalNotes:secret});
  await call('/api/content','PUT',{content,revision:0},owner);
  await call('/api/users','GET',undefined,{},401);
  await call('/api/users','POST',{username:'anonymous',role:'admin'},{},401);
  await call('/api/users','POST',{username:'staff',role:'admin'},{Cookie:owner.Cookie},403);
  const created = (await call('/api/users','POST',{username:'inventory-editor',role:'editor',permissions:['inventory.write']},owner,201)).data;
  assert.ok(created.temporaryPassword.length>=24);
  assert.deepEqual(created.user.permissions,['inventory.read','inventory.write']);
  const pending = await call('/api/login','POST',{username:'INVENTORY-EDITOR',password:created.temporaryPassword});
  const tempAuth = authentication(pending);
  assert.equal(pending.data.mustChangePassword,true);
  for(const route of ['/api/admin/overview','/api/users','/api/logs','/api/backups','/api/media']) await call(route,'GET',undefined,tempAuth,403);
  await call('/api/content','PUT',{content,revision:1},tempAuth,403);
  assert.ok(!(await call('/api/content','GET',undefined,tempAuth)).data.content.listings.some(x=>x.status==='draft'));
  await call('/api/account/password','POST',{currentPassword:created.temporaryPassword,newPassword:'short',confirmPassword:'short'},tempAuth,400);
  const newPassword = randomBytes(28).toString('base64url');
  await call('/api/account/password','POST',{currentPassword:'incorrect',newPassword,confirmPassword:newPassword},tempAuth,400);
  const changed = await call('/api/account/password','POST',{currentPassword:created.temporaryPassword,newPassword,confirmPassword:newPassword},tempAuth);
  const staff = authentication(changed);
  assert.equal(changed.data.mustChangePassword,false);
  assert.equal((await call('/api/session','GET',undefined,tempAuth)).data.authenticated,false);
  await call('/api/login','POST',{username:'inventory-editor',password:created.temporaryPassword},{},401);
  await call('/api/admin/overview','GET',undefined,staff);
  for(const route of ['/api/users','/api/logs','/api/backups','/api/media']) await call(route,'GET',undefined,staff,403);
  const partial = (await call('/api/content','GET',undefined,staff)).data;
  assert.ok(partial.content.listings.some(x=>x.id==='inventory-draft'));
  assert.ok(!partial.content.listings.some(x=>x.id==='wanted-draft'));
  partial.content.listings.find(x=>x.id==='inventory-draft').model='Updated test automobile';
  await call('/api/content','PUT',partial,staff);
  const all = (await call('/api/content','GET',undefined,owner)).data;
  assert.equal(all.content.listings.find(x=>x.id==='wanted-draft').internalNotes,secret);
  const forbidden = (await call('/api/content','GET',undefined,staff)).data;
  forbidden.content.listings.find(x=>x.type==='wanted').model='Unauthorized edit';
  await call('/api/content','PUT',forbidden,staff,403);
  const settings = (await call('/api/content','GET',undefined,staff)).data;
  settings.content.settings.headline='Unauthorized headline';
  await call('/api/content','PUT',settings,staff,403);
  const logs = (await call('/api/logs','GET',undefined,owner)).data;
  assert.ok(logs.events.some(event=>event.actor.username==='inventory-editor'&&event.action==='content.save'));
  const serialized = JSON.stringify(logs);
  for(const sensitive of [secret,created.temporaryPassword,newPassword,hash,salt]) assert.ok(!serialized.includes(sensitive),'Audit secret redaction');
  assert.ok(logs.events.some(event=>event.action==='account.password_changed'));
  const listing = (await call('/api/users','GET',undefined,owner)).data;
  assert.ok(!JSON.stringify(listing).includes(created.temporaryPassword));
  await call('/api/users/owner','PUT',{disabled:true},owner,403);
  await call('/api/users/'+created.user.id,'PUT',{disabled:true},owner);
  assert.equal((await call('/api/session','GET',undefined,staff)).data.authenticated,false);
  await call('/api/login','POST',{username:'inventory-editor',password:newPassword},{},401);
  const reset = (await call('/api/users/'+created.user.id+'/reset-password','POST',{},owner)).data;
  assert.ok(reset.temporaryPassword&&reset.temporaryPassword!==created.temporaryPassword);
  await call('/api/users/'+created.user.id,'PUT',{disabled:false},owner);
  const resetLogin = await call('/api/login','POST',{username:'inventory-editor',password:reset.temporaryPassword});
  assert.equal(resetLogin.data.mustChangePassword,true);
  await call('/api/logout','POST',{},authentication(resetLogin));
  const expiryLogin = await call('/api/login','POST',{username:'inventory-editor',password:reset.temporaryPassword});
  const beforeExpiry = await DB.prepare('SELECT hash FROM staff_users WHERE id = ?').bind(created.user.id).first();
  env.DB = {...DB, async batch(statements) {
    await DB.prepare('UPDATE staff_users SET temp_expires_at = ? WHERE id = ?').bind(Math.floor(Date.now()/1000)-1,created.user.id).run();
    return DB.batch(statements);
  }};
  await call('/api/account/password','POST',{currentPassword:reset.temporaryPassword,newPassword,confirmPassword:newPassword},authentication(expiryLogin),409);
  env.DB = DB;
  assert.equal((await DB.prepare('SELECT hash FROM staff_users WHERE id = ?').bind(created.user.id).first()).hash,beforeExpiry.hash,'Expired temporary password cannot finish an in-flight password change');
  assert.equal((await call('/api/session','GET',undefined,authentication(expiryLogin))).data.authenticated,false);
  assert.equal((await call('/api/session','GET',undefined,owner)).data.authenticated,true);
  console.log(`PASS: ${assertions} staff API checks, forced password replacement, permission boundaries, private data preservation, owner protection, audit attribution, reset, revocation and in-flight temporary expiry.`);
} finally { DB.close(); }
